version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "3500:3500"
    environment:
      DATABASE_URI: mongodb+srv://arafahlawal:Santos.jnr10!@cluster0.ukwcdk8.mongodb.net/?retryWrites=true&w=majority
  events:
    build: ./events
    ports:
      - "5000:5000"
    depends_on:
      - api
