version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    volumes:
      - ./api:/usr/src/api
    environment:
      - NODE_ENV=development
      - MONGO_URI=${DATABASE_URI}
    depends_on:
      - events

  events:
    build:
      context: ./events
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./events:/app
